/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MechApp.vista;

import MechApp.controlador.MecanicaMateriales;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Locale;


/**
Propósito de la aplicación:
Proyecto Silver1, aplicaciones varias para uso en Ingeniería Mecánica (Español)


Registro de revisiones:

Fecha        Programador          Descripción de cambios
======       ===========          =======================
12/01/2021   Edilson Sarmiento    Código original

**/
public class VentanaPrincipal extends javax.swing.JFrame {
   
    /**
     * Creates new form VentanaPrincipal
     */
       
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_tituloEstado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jB_calcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTF_sigmaX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jL_unidadesSigmaX = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jL_unidadesSigmaY = new javax.swing.JLabel();
        jTF_sigmaY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTF_tauXY = new javax.swing.JTextField();
        jL_unidadesTauXY = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTF_theta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jL_unidadesTauX1Y1 = new javax.swing.JLabel();
        jTF_tauX1Y1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTF_sigmaY1 = new javax.swing.JTextField();
        jL_unidadesSigmaY1 = new javax.swing.JLabel();
        jL_unidadesSigmaX1 = new javax.swing.JLabel();
        jTF_sigmaX1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCB_seleccionUnidades = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jB_limpiarCampos = new javax.swing.JButton();
        jB_formulasEPEII = new javax.swing.JButton();
        jL_mensajeEstado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTF_sigma1 = new javax.swing.JTextField();
        jL_unidadesSigma1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTF_sigma2 = new javax.swing.JTextField();
        jL_unidadesSigma2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTF_thetap1 = new javax.swing.JTextField();
        jL_unidadesSigma3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTF_thetap2 = new javax.swing.JTextField();
        jL_unidadesSigma5 = new javax.swing.JLabel();
        jL_unidadesSigma6 = new javax.swing.JLabel();

        jL_tituloEstado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jL_tituloEstado.setText("Estado:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estado de esfuerzo plano");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 4,
            Toolkit.getDefaultToolkit().getScreenSize().height / 13);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Propósito: Cálculo de esfuerzo plano en un elemento infinitesimal inclinado.");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB_calcular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_calcular.setText("Calcular");
        jB_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_calcularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/MechApp_logo_small.png"))); // NOI18N

        jTF_sigmaX.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_sigmaX.setEnabled(false);
        jTF_sigmaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sigmaXActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Ingresar los datos correspondientes:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_unidadesSigmaX.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigmaX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigmaX.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigmaX.setText("---");
        jL_unidadesSigmaX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Esfuerzo normal x:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_unidadesSigmaY.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigmaY.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigmaY.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigmaY.setText("---");
        jL_unidadesSigmaY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_sigmaY.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_sigmaY.setEnabled(false);
        jTF_sigmaY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sigmaYActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Esfuerzo normal y:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Esfuerzo cortante xy:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_tauXY.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_tauXY.setEnabled(false);
        jTF_tauXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_tauXYActionPerformed(evt);
            }
        });

        jL_unidadesTauXY.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesTauXY.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesTauXY.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesTauXY.setText("---");
        jL_unidadesTauXY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Ángulo inclinación:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_theta.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_theta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_thetaActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("[Grados]");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Resultados:");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_unidadesTauX1Y1.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesTauX1Y1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesTauX1Y1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesTauX1Y1.setText("---");
        jL_unidadesTauX1Y1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_tauX1Y1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_tauX1Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_tauX1Y1ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Esfuerzo cortante x1y1:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Esfuerzo normal y1:");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_sigmaY1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_sigmaY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sigmaY1ActionPerformed(evt);
            }
        });

        jL_unidadesSigmaY1.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigmaY1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigmaY1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigmaY1.setText("---");
        jL_unidadesSigmaY1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_unidadesSigmaX1.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigmaX1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigmaX1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigmaX1.setText("---");
        jL_unidadesSigmaX1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_sigmaX1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_sigmaX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sigmaX1ActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Esfuerzo normal x1:");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/EsfuerzosInclinados_1.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Tomado de: ");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jCB_seleccionUnidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCB_seleccionUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin selección", "Unidades métricas [MPa]", "Unidades inglesas [psi]" }));
        jCB_seleccionUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_seleccionUnidadesActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Seleccionar unidades: ");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Mechanics of Materials [9 Ed], J. Gere, B. Goodno");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jB_limpiarCampos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jB_limpiarCampos.setText("Limpiar campos");
        jB_limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_limpiarCamposActionPerformed(evt);
            }
        });

        jB_formulasEPEII.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jB_formulasEPEII.setText("Fórmulas");
        jB_formulasEPEII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_formulasEPEIIActionPerformed(evt);
            }
        });

        jL_mensajeEstado.setBackground(new java.awt.Color(255, 255, 255));
        jL_mensajeEstado.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jL_mensajeEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_mensajeEstado.setText("Esperando acción...");
        jL_mensajeEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Sigma_x1.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Sigma_y1.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Tau_x1y1.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Theta.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Tau_xy.png"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Sigma_y.png"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Sigma_x.png"))); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Sigma_1.png"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Esfuerzo principal 1:");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_sigma1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_sigma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sigma1ActionPerformed(evt);
            }
        });

        jL_unidadesSigma1.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigma1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigma1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigma1.setText("---");
        jL_unidadesSigma1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Sigma_2.png"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Esfuerzo principal 2:");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_sigma2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_sigma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_sigma2ActionPerformed(evt);
            }
        });

        jL_unidadesSigma2.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigma2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigma2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigma2.setText("---");
        jL_unidadesSigma2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Theta_p1.png"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Ángulo principal 1:");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_thetap1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_thetap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_thetap1ActionPerformed(evt);
            }
        });

        jL_unidadesSigma3.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigma3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigma3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigma3.setText("[Grados]");
        jL_unidadesSigma3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MechApp/vista/images/Theta_p2.png"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Ángulo principal 2:");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTF_thetap2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTF_thetap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_thetap2ActionPerformed(evt);
            }
        });

        jL_unidadesSigma5.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigma5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jL_unidadesSigma5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigma5.setText("Estado: ");
        jL_unidadesSigma5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_unidadesSigma6.setBackground(new java.awt.Color(255, 255, 255));
        jL_unidadesSigma6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jL_unidadesSigma6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jL_unidadesSigma6.setText("[Grados]");
        jL_unidadesSigma6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_sigmaY, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigmaY, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_sigmaX, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigmaX, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTF_theta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jTF_tauXY, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_unidadesTauXY, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jTF_sigma1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jL_unidadesSigma1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_sigmaX1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigmaX1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_sigmaY1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigmaY1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_tauX1Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesTauX1Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_sigma2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigma2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_thetap1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigma3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTF_thetap2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jL_unidadesSigma6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel30)
                                    .addComponent(jL_unidadesSigma5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jL_mensajeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCB_seleccionUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 47, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jB_limpiarCampos)
                                .addGap(27, 27, 27)
                                .addComponent(jB_formulasEPEII)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jB_calcular)
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCB_seleccionUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_sigmaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jL_unidadesSigmaX)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTF_sigmaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_unidadesSigmaY)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_tauXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jL_unidadesTauXY))
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_theta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10))
                            .addComponent(jLabel13))
                        .addGap(11, 11, 11)
                        .addComponent(jB_calcular)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jTF_sigmaX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_unidadesSigmaX1))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jL_unidadesSigmaY1)
                                .addComponent(jTF_sigmaY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_tauX1Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_unidadesTauX1Y1)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_sigma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_unidadesSigma1)
                                .addComponent(jLabel25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_thetap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_unidadesSigma3)
                                .addComponent(jLabel29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTF_sigma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jL_unidadesSigma2)
                                .addComponent(jLabel27)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jTF_thetap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(jL_unidadesSigma6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL_mensajeEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jL_unidadesSigma5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_formulasEPEII)
                        .addComponent(jB_limpiarCampos)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_calcularActionPerformed
        calcularEsfuerzosInclinados();
    }//GEN-LAST:event_jB_calcularActionPerformed

    private void jTF_sigmaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sigmaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sigmaXActionPerformed

    private void jTF_sigmaYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sigmaYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sigmaYActionPerformed

    private void jTF_tauXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_tauXYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_tauXYActionPerformed

    private void jTF_thetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_thetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_thetaActionPerformed

    private void jTF_tauX1Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_tauX1Y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_tauX1Y1ActionPerformed

    private void jTF_sigmaY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sigmaY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sigmaY1ActionPerformed

    private void jTF_sigmaX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sigmaX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sigmaX1ActionPerformed

    private void jCB_seleccionUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_seleccionUnidadesActionPerformed
        seleccionarUnidades();
    }//GEN-LAST:event_jCB_seleccionUnidadesActionPerformed

    private void jB_limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_limpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jB_limpiarCamposActionPerformed

    private void jB_formulasEPEIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_formulasEPEIIActionPerformed
        mostrarFormulasEPEII();
    }//GEN-LAST:event_jB_formulasEPEIIActionPerformed

    private void jTF_sigma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sigma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sigma1ActionPerformed

    private void jTF_sigma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_sigma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_sigma2ActionPerformed

    private void jTF_thetap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_thetap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_thetap1ActionPerformed

    private void jTF_thetap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_thetap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_thetap2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_calcular;
    private javax.swing.JButton jB_formulasEPEII;
    private javax.swing.JButton jB_limpiarCampos;
    private javax.swing.JComboBox<String> jCB_seleccionUnidades;
    private javax.swing.JLabel jL_mensajeEstado;
    private javax.swing.JLabel jL_tituloEstado;
    private javax.swing.JLabel jL_unidadesSigma1;
    private javax.swing.JLabel jL_unidadesSigma2;
    private javax.swing.JLabel jL_unidadesSigma3;
    private javax.swing.JLabel jL_unidadesSigma5;
    private javax.swing.JLabel jL_unidadesSigma6;
    private javax.swing.JLabel jL_unidadesSigmaX;
    private javax.swing.JLabel jL_unidadesSigmaX1;
    private javax.swing.JLabel jL_unidadesSigmaY;
    private javax.swing.JLabel jL_unidadesSigmaY1;
    private javax.swing.JLabel jL_unidadesTauX1Y1;
    private javax.swing.JLabel jL_unidadesTauXY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_sigma1;
    private javax.swing.JTextField jTF_sigma2;
    private javax.swing.JTextField jTF_sigmaX;
    private javax.swing.JTextField jTF_sigmaX1;
    private javax.swing.JTextField jTF_sigmaY;
    private javax.swing.JTextField jTF_sigmaY1;
    private javax.swing.JTextField jTF_tauX1Y1;
    private javax.swing.JTextField jTF_tauXY;
    private javax.swing.JTextField jTF_theta;
    private javax.swing.JTextField jTF_thetap1;
    private javax.swing.JTextField jTF_thetap2;
    // End of variables declaration//GEN-END:variables
    
    
    
    // Métodos para GUI
    
    // -------------  Métodos para aplicación de Esfuerzos Planos -------------
    
    private void seleccionarUnidades() {
        String seleccion = (String)jCB_seleccionUnidades.getSelectedItem();
        String unidades = "---";
                        
        if (seleccion.equals("Sin selección")) {    
            unidades = "---";
            jL_unidadesSigmaX.setText(unidades);
            jL_unidadesSigmaY.setText(unidades);
            jL_unidadesTauXY.setText(unidades);
            jL_unidadesSigmaX1.setText(unidades);
            jL_unidadesSigmaY1.setText(unidades);
            jL_unidadesTauX1Y1.setText(unidades);
            jL_unidadesSigma1.setText(unidades);
            jL_unidadesSigma2.setText(unidades);
            jTF_sigmaX.setEnabled(false);
            jTF_sigmaY.setEnabled(false);
            jTF_tauXY.setEnabled(false);            
        } else if (seleccion.equals("Unidades métricas [MPa]")) {
            unidades = "[MPa]";
            jL_unidadesSigmaX.setText(unidades);
            jL_unidadesSigmaY.setText(unidades);
            jL_unidadesTauXY.setText(unidades);
            jL_unidadesSigmaX1.setText(unidades);
            jL_unidadesSigmaY1.setText(unidades);
            jL_unidadesTauX1Y1.setText(unidades);
            jL_unidadesSigma1.setText(unidades);
            jL_unidadesSigma2.setText(unidades);
            jTF_sigmaX.setEnabled(true);
            jTF_sigmaY.setEnabled(true);
            jTF_tauXY.setEnabled(true);
        } else if (seleccion.equals("Unidades inglesas [psi]")) {
            unidades = "[psi]";
            jL_unidadesSigmaX.setText(unidades);
            jL_unidadesSigmaY.setText(unidades);
            jL_unidadesTauXY.setText(unidades);
            jL_unidadesSigmaX1.setText(unidades);
            jL_unidadesSigmaY1.setText(unidades);
            jL_unidadesTauX1Y1.setText(unidades);
            jL_unidadesSigma1.setText(unidades);
            jL_unidadesSigma2.setText(unidades);
            jTF_sigmaX.setEnabled(true);
            jTF_sigmaY.setEnabled(true);
            jTF_tauXY.setEnabled(true);
        }  
    }
    
    
    private void calcularEsfuerzosInclinados() {
        double sigma_x = Double.parseDouble(jTF_sigmaX.getText());
        double sigma_y = Double.parseDouble(jTF_sigmaY.getText());
        double tau_xy = Double.parseDouble(jTF_tauXY.getText());
        double theta = Double.parseDouble(jTF_theta.getText());
        try {
            double esfuerzosEntrada[] = {sigma_x, sigma_y, tau_xy};
            double esfuerzosSalida[] = MecanicaMateriales.esfuerzosInclinados(esfuerzosEntrada, theta);
            String sigma_x1 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[0]);
            String sigma_y1 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[1]);
            String tau_x1y1 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[2]);
            String sigma_1 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[3]);
            String sigma_2 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[4]);
            String theta_p1 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[5]);
            String theta_p2 = String.format(Locale.ENGLISH, "%.2f%n", esfuerzosSalida[6]);
            jTF_sigmaX1.setText(sigma_x1);
            jTF_sigmaY1.setText(sigma_y1);
            jTF_tauX1Y1.setText(tau_x1y1);
            jTF_sigma1.setText(sigma_1);
            jTF_sigma2.setText(sigma_2);
            jTF_thetap1.setText(theta_p1);
            jTF_thetap2.setText(theta_p2);
            jL_mensajeEstado.setForeground(new Color(51,153,0)); // Texto color verde
            jL_mensajeEstado.setText("Cálculos ejecutados correctamente.");
            System.out.println("Correcto");
        }
        catch (Exception e) {
            System.out.println("Error");
            jL_mensajeEstado.setForeground(new Color(204,0,51)); // Texto color rojo
            jL_mensajeEstado.setText("Ocurrió algún error. Por favor verifica los datos ingresados.");
        }      
    }
    
    private void limpiarCampos() {
        jTF_sigmaX.setText("");
        jTF_sigmaY.setText("");
        jTF_tauXY.setText("");
        jTF_theta.setText("");

        jTF_sigmaX1.setText("");
        jTF_sigmaY1.setText("");
        jTF_tauX1Y1.setText("");
        jTF_sigma1.setText("");
        jTF_sigma2.setText("");
        jTF_thetap1.setText("");
        jTF_thetap2.setText("");
        
        jL_mensajeEstado.setForeground(Color.black);
        jL_mensajeEstado.setText("Esperando acción...");
        
    }

    private void mostrarFormulasEPEII() {
        new Formulas_EPEII().setVisible(true);
    }
}
    
    //double prueba[] = MecanicaMateriales.esfuerzosInclinados(, );



